### ISSUE TITLE
JPX ColorSpace can be overridden, but the rules for its "colr" box still apply

### ISSUE THREAD

**Issue by bdoubrov** [pdf-association/pdf-issues#167]
This is the mirror of the issue https://github.com/pdf-association/pdfa-twg/issues/9 discussed and resolved at the PDF/A TWG.

The following PDF/A-4 requirements on JPEG 2000 (and only they) are related to **colr** box in JPX stream and shall be ignored in presence of **ColorSpace** entry in the parent Image XObject dictionary (ISO 19005-4, 6.2.7.3 JPEG2000) :

> If the number of colour space specifications in the JPEG2000 data is greater than 1, there shall be exactly
one colour space specification that has the value 0x01 in the APPROX field. If the specified colour space
specification uses an ICC profile, then that profile shall conform to the requirements of ISO 32000-2:2020,
8.6.5.5.

> The value of the METH entry in its ‘colr’ box shall be 0x01, 0x02 or 0x03. A conforming processor shall
use only that colour space and shall ignore all other colour space specifications.

> JPEG2000 enumerated colour space 19 (CIEJab) shall not be used.

> JPEG2000 enumerated colour space 12 (CMYK) which is part of JPX but not JPX baseline, may be used.

All other requirement from ISO 19005-4:2020, 6.2.7.3 such as the number of colour channels and the bit-depth of the JPEG2000 data are defined in other box types and stay independently of absence or presence of the **ColorSpace** entry in the Image XObject dictionary.

**Comment by petervwyatt** [comment]
This is what I believe the final wording/layout for PDF/A-4 will be. The same identical change is also needed for PDF/X-6 in clause 6.7.4.3 to keep PDF/A-4 and PDF/X-6 synchronized:

**6.2.7.3 JPEG2000**

When used, JPEG2000 compression shall be used as specified in ISO 32000-2:—. Only the JPX baseline set of features, as restricted or extended by ISO 32000-2:—, and this subclause, shall be used.

NOTE 1 The JPX baseline set of features is defined in ISO/IEC 15444-2 M 9.2.

The number of colour channels in the JPEG2000 data shall be 1, 3 or 4.

The following list of PDF/A-4 JPEG2000 requirements relate only to the ‘colr’ box in the JPX stream and shall be ignored in presence of **ColorSpace** entry in the parent Image XObject dictionary:

- If the number of colour space specifications in the JPEG2000 data is greater than 1, there shall be exactly one colour space specification that has the value 0x01 in the **APPROX** field. If the specified colour space specification uses an ICC profile, then that profile shall conform to the requirements of ISO 32000-2:—, 8.6.5.5.

NOTE 2 The value 0x01 in the **APPROX** field identifies the colour space with the best colour fidelity available.

- The value of the **METH** entry in its ‘colr’ box shall be 0x01, 0x02 or 0x03. A conforming processor shall use only that colour space and shall ignore all other colour space specifications.

- JPEG2000 enumerated colour space 19 (CIEJab) shall not be used.

- JPEG2000 enumerated colour space 12 (CMYK) which is part of JPX but not JPX baseline, may be used.

Where the JPEG2000 image effectively uses **DeviceGray**, **DeviceRGB** or **DeviceCMYK** – whether through the **ColorSpace** entry in the Image XObject or in the absence thereof through the colour space definition in the JPEG2000 data, the provisions of 6.2.4.3 shall apply.

…

**Comment by lrosenthol** [comment]
Sorry, but I don't see any reason to do this.  The current text is correct as is.

**Comment by petervwyatt** [comment]
This issue will return to PDF/A TWG for further discussion. 
Once resolved in PDF/A TWG, the PDF/X impact will be discussed in PDF TWG in the future.

**Comment by petervwyatt** [comment]
Closing here now. Can be re-opened by PDF/A TWG if required

**Comment by lrosenthol** [comment]
If we were going to make any change - and I am still not convinced it is necessary - I would do the following:

>The value of the METH entry in its ‘colr’ box shall be 0x01, 0x02 or 0x03. A conforming reader shall use only that colour space and shall ignore all other colour space specifications.

change the second half to add:

When a ColorSpace entry is not present on the Image XObject, then a conforming reader shall...
