### ISSUE TITLE
PDF/A-4: DestOutputProfile

### ISSUE THREAD

**Issue by a20dev** [pdf-association/pdf-issues#631]
The wording in ISO 19005-4:2020 6.2.3 seems to allow different OutputIntents arrays to have elements that have DestOutputProfile entries that point to different indirect objects. 

For instance, the current wording allows a document to have in its document catalog an OutputIntents array containing one element that is a PDF/X-4 output intent and for each page an OutputIntents array containing one element that is a PDF/A output intent and all these output intents may have DestOutputProfile entries pointing to different indirect objects. Is this interpretation of 6.2.3 correct? And is this interpretation intended?

On the other hand, 6.2.3 prohibits the same document from having for each page an OutputIntents array containing two elements, one for PDF/X-4 and one for PDF/A having DestOutputProfile entries pointing to different indirect objects.

14.11.5 of ISO 32000-2:2020 does not really specify whether those ways of declaring output intents are equivalent or not:

```
If a PDF processor chooses to respect output intents, then when processing a
page that has an associated (page-level) output intent, that page-level output intent shall be used.

```

Note that 14.11.5 does not specify that if a page object has an OutputIntents entry, that array shall completely override the document catalog's OutputIntents entry. Rather, it talks of "an [...] output intent".  Am I missing something?

BTW, 6.2.3 of ISO 19005-4:2020 is a bit difficult to read because it refers to the elements of an array as "entries". ISO 32000 uses "elements".

**Comment by a20dev** [comment]
Maybe the best solution is to specify that if a page object contains an OutputIntents entry, that OutputIntents entry completely overrides any OutputIntents entry (ie, all its elements) in the document catalog for that page. That way, elements of a page's OutputIntents will never be mixed with elements of the document catalog's OutputIntents and all output intents of a page will share the same DestOutputProfile stream. Also, it will still be possible to have pages with, say, RGB output intents and pages with, say, CMYK output intents in the same document.

**Comment by petervwyatt** [comment]
I believe all points will be adequately addressed in the forthcoming DIS of PDF/A-4 dated revision.

**Comment by a20dev** [comment]
Can you leak the new wording? The latest draft I could find is N1768 and it doesn't fix this issue.
